language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t rbiagtan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rbiagtan/docker-react npm run test