language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t rbiagtan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rbiagtan/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-986424544712"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  

